apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.redis_image.repository }}:{{ .Values.redis_image.tag }}
    name: redis
    ports:
    - containerPort: {{ .Values.service.spec.containerPort }}
      protocol: {{ .Values.service.spec.protocol }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
