apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.nginx_image.repository }}:{{ .Values.nginx_image.tag }}
    name: nginx
    resources:
      limits:      
      - memory: {{ .Values.resources.limits.memory }}
        cpu: {{ .Values.resources.limits.cpu }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
